using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;

using UnityEngine;
using UnityEditor;

using Edger.Unity;

namespace Edger.Unity.Editor {
    public static class UnityConstsGenerator {
        public const string UNITY_CONSTS_PATH = "Assets/Scripts/UnityConsts.cs";

        public static string GetConstName(string name) {
            return name.Replace(' ', '_');
        }

        public static void WriteLinesToFile(List<string> lines, string path) {
            StringBuilder builder = new StringBuilder();
            foreach (var line in lines) {
                builder.Append(line);
                builder.Append("\n");
            }

            FileUtil.WriteFile(path, builder.ToString());
        }

        public static void GenerateUnityConsts(string path, Action<List<string>> callback) {
            List<string> lines = new List<string>();
            lines.AddLine("/* Do NOT Modify, Generated by Edger.Unity.Editor.UnityConstsGenerator */");
            lines.AddLine("/* Generated At: {0} */", DateTimeUtil.UtcTimestamp);
            lines.AddLine("");
            lines.AddLine("using System;");
            lines.AddLine("");
            lines.AddLine("using Edger.Unity;");
            lines.AddLine("");
            lines.AddLine("public static class UnityConsts {");
            callback(lines);
            lines.AddLine("}");

            WriteLinesToFile(lines, path);
            Log.Info("UnityConsts Generated: {0}", path);
        }

        private static void AddUnityLayersToLines(List<string> lines) {
            for (int i = 0; i < 32; i++) {
                string layerName = LayerMask.LayerToName(i);
                if (!string.IsNullOrEmpty(layerName)) {
                    lines.AddLine("    public const int LAYER_{0} = {1};",
                            GetConstName(layerName), i);
                }
            }
            lines.AddLine("");
            for (int i = 0; i < 32; i++) {
                string layerName = LayerMask.LayerToName(i);
                if (!string.IsNullOrEmpty(layerName)) {
                    lines.AddLine("    public const string LAYER_NAME_{0} = \"{1}\"; //{2}",
                            GetConstName(layerName), layerName, i);
                }
            }
        }

        private static void AddUnitySortingLayersToLines(List<string> lines) {
            foreach (SortingLayer layer in SortingLayer.layers) {
                lines.AddLine("    public const int SORTING_LAYER_{0} = {1};",
                        GetConstName(layer.name), layer.id);
            }
            lines.AddLine("");
            foreach (SortingLayer layer in SortingLayer.layers) {
                lines.AddLine("    public const string SORTING_LAYER_NAME_{0} = \"{1}\";",
                        GetConstName(layer.name), layer.name);
            }
            lines.AddLine("");
            foreach (SortingLayer layer in SortingLayer.layers) {
                lines.AddLine("    public const int SORTING_LAYER_VALUE_{0} = {1};",
                        GetConstName(layer.name), layer.value);
            }
        }

        private static void AddUnityTagsToLines(List<string> lines) {
            // http://answers.unity3d.com/questions/57952/getting-the-tag-array.html
            foreach (string tag in UnityEditorInternal.InternalEditorUtility.tags) {
                lines.AddLine("    public const string TAG_{0} = \"{1}\";",
                        GetConstName(tag), tag);
            }
        }

        private static void AddUnityLines(List<string> lines) {
            AddUnityTagsToLines(lines);
            lines.AddLine("");
            AddUnityLayersToLines(lines);
            lines.AddLine("");
            AddUnitySortingLayersToLines(lines);
        }

        public static void GenerateConsts(string path=UNITY_CONSTS_PATH) {
            GenerateUnityConsts(path, AddUnityLines);
            AssetDatabase.Refresh();
        }
    }
}
